name: Clone and Process Repository

on:
  push:
    branches:
      - main

jobs:
  clone-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clone Public Repository
      run: |
        git clone https://github.com/Anduin2017/HowToCook.git /tmp/target-repo

    - name: Translation Files
      run: |
        ls
        chmod +x ./bin/HowToCook-json_linux_amd64_v1/HowToCook-json
        ./bin/HowToCook-json_linux_amd64_v1/HowToCook-json /tmp/target-repo/dishes ../json
        ls
        ls ./
